apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-deployment
  labels:
    app: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
        - name: playground
          image: wil42/playground:v1
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: playground-service
  labels:
    app: playground
spec:
  selector:
    app: playground
  ports:
    - port: 8888           # Porta que o serviço expõe
      targetPort: 8000     # Porta dentro do container
      nodePort: 30088      # Porta exposta no host da sua máquina (qualquer valor entre 30000–32767)
      protocol: TCP
  type: NodePort
