apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-deployment
  labels:
    app: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
        - name: web
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: playground-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: playground-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Playground</title>
      <meta charset="utf-8" />
      <style>
        body { font-family: sans-serif; display:flex; align-items:center; justify-content:center; height:100vh; margin:0; background:#111; color:#0f0; }
        .box { text-align:center; }
      </style>
    </head>
    <body>
      <div class="box">
        <h1>Argo CD 🚀 Mudei isso aqui!</h1>
        <p>Deploy via GitOps funcionando!</p>
      </div>
    </body>
    </html>
