apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-deployment
  labels:
    app: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
        - name: playground
          image: wil42/playground:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: playground-service
  labels:
    app: playground
spec:
  type: NodePort
  selector:
    app: playground
  ports:
    - name: http
      port: 8888        # porta do serviço dentro do cluster
      targetPort: 8888  # porta do container (imagem do wil42)
      nodePort: 30088   # exposta no node (mapeada para http://localhost:8888 pelo k3d)
      protocol: TCP
