apiVersion: v1
kind: Service
metadata:
  name: playground-service
  labels:
    app: playground
spec:
  selector:
    app: playground
  ports:
    - port: 8888
      targetPort: 80
      protocol: TCP
